BannerShop:
  PatternPrices:
    PATTERN_BOTTOM_STRIPE: 70
    PATTERN_TOP_STRIPE: 70
    PATTERN_LEFT_STRIPE: 70
    PATTERN_RIGHT_STRIPE: 70
    PATTERN_CENTER_STRIPE: 70
    PATTERN_MIDDLE_STRIPE: 70
    PATTERN_DOWN_RIGHT_STRIPE: 70
    PATTERN_DOWN_LEFT_STRIPE: 70
    PATTERN_SMALL_STRIPES: 70
    PATTERN_DIAGONAL_CROSS: 70
    PATTERN_SQUARE_CROSS: 70
    PATTERN_LEFT_OF_DIAGONAL: 70
    PATTERN_RIGHT_OF_UPSIDE_DOWN_DIAGONAL: 70
    PATTERN_LEFT_OF_UPSIDE_DOWN_DIAGONAL: 70
    PATTERN_RIGHT_OF_DIAGONAL: 70
    PATTERN_VERTICAL_HALF_LEFT: 70
    PATTERN_VERTICAL_HALF_RIGHT: 70
    PATTERN_HORIZONTAL_HALF_TOP: 70
    PATTERN_HORIZONTAL_HALF_BOTTOM: 70
    PATTERN_BOTTOM_LEFT_CORNER: 70
    PATTERN_BOTTOM_RIGHT_CORNER: 70
    PATTERN_TOP_LEFT_CORNER: 200
    PATTERN_TOP_RIGHT_CORNER: 200
    PATTERN_BOTTOM_TRIANGLE: 200
    PATTERN_TOP_TRIANGLE: 200
    PATTERN_BOTTOM_TRIANGLE_SAWTOOTH: 200
    PATTERN_TOP_TRIANGLE_SAWTOOTH: 200
    PATTERN_MIDDLE_CIRCLE: 200
    PATTERN_MIDDLE_RHOMBUS: 200
    PATTERN_BORDER: 200
    PATTERN_CURLY_BORDER: 200
    PATTERN_BRICK: 500
    PATTERN_GRADIENT: 500
    PATTERN_GRADIENT_UPSIDE_DOWN: 500
    PATTERN_CREEPER: 500
    PATTERN_SKULL: 500
    PATTERN_FLOWER: 500
    PATTERN_MOJANG: 500

Commands:
  Banner:
    Name: "banner"
    Description: "Buy your own Banner"
    Permission: "llamabanners.command.banner"
    Aliases: [ "bannershop", "bshop" ]
